#ifndef __OpenViBEToolkit_ScenarioIO_H__
#define __OpenViBEToolkit_ScenarioIO_H__

#define OVTK_Algorithm_ScenarioExporter_NodeId_OpenViBEScenario                         OpenViBE::CIdentifier(0x1CD93114, 0x6A544E8C)

#define OVTK_Algorithm_ScenarioExporter_NodeId_Boxes                                    OpenViBE::CIdentifier(0x4BCB7EA2, 0x49B95B54)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Box                                      OpenViBE::CIdentifier(0xF7341CA6, 0x05DBB935)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Box_Identifier                           OpenViBE::CIdentifier(0x388E37B5, 0x3F471DB7)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Box_Name                                 OpenViBE::CIdentifier(0x5472B291, 0x51F94B43)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Box_AlgorithmClassIdentifier             OpenViBE::CIdentifier(0x2CBBE45B, 0xD9385308)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Box_Inputs                               OpenViBE::CIdentifier(0xB07E43FA, 0x3BFB5C41)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Box_Input                                OpenViBE::CIdentifier(0x7B149417, 0x39F0D7BC)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Box_Input_TypeIdentifier                 OpenViBE::CIdentifier(0xC7D436D2, 0x7C808FAD)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Box_Input_Name                           OpenViBE::CIdentifier(0xA65B1B6D, 0x70799D8F)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Box_Outputs                              OpenViBE::CIdentifier(0xD5CBFF2C, 0x349EED80)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Box_Output                               OpenViBE::CIdentifier(0x8FE44764, 0xB6E9EEDE)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Box_Output_TypeIdentifier                OpenViBE::CIdentifier(0x7C3CEAC8, 0x55E5B85F)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Box_Output_Name                          OpenViBE::CIdentifier(0x858B86C9, 0x8FDE0A88)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Box_Settings                             OpenViBE::CIdentifier(0x456F426E, 0xD5F745C0)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Box_Setting                              OpenViBE::CIdentifier(0x6D781687, 0xEC0697F0)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Box_Setting_TypeIdentifier               OpenViBE::CIdentifier(0x4E025442, 0xF15A306B)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Box_Setting_Name                         OpenViBE::CIdentifier(0xF653238C, 0xCF13CC1E)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Box_Setting_DefaultValue                 OpenViBE::CIdentifier(0x22B803B1, 0xB99EB29C)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Box_Setting_Value                        OpenViBE::CIdentifier(0x4B157087, 0xA17AC752)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Box_Attributes                           OpenViBE::CIdentifier(0x5A512182, 0xEA975174)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Box_Attribute                            OpenViBE::CIdentifier(0xAAE1C0BA, 0x0CCB4F6E)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Box_Attribute_Identifier                 OpenViBE::CIdentifier(0xFDE975E7, 0x9EE828E5)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Box_Attribute_Value                      OpenViBE::CIdentifier(0x08700489, 0x15D4C296)

#define OVTK_Algorithm_ScenarioExporter_NodeId_Comments                                 OpenViBE::CIdentifier(0x05FFFB9C, 0x0D3F72B9)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Comment                                  OpenViBE::CIdentifier(0x8A90B4C7, 0x1B1F91C8)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Comment_Identifier                       OpenViBE::CIdentifier(0x5D5AC202, 0x8A8A2049)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Comment_Text                             OpenViBE::CIdentifier(0xE1FBD2D0, 0x62644098)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Comment_Attributes                       OpenViBE::CIdentifier(0x03A34281, 0x49A94884)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Comment_Attribute                        OpenViBE::CIdentifier(0xD1BE5B9E, 0x290F273E)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Comment_Attribute_Identifier             OpenViBE::CIdentifier(0x4A68A79B, 0x26590AC7)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Comment_Attribute_Value                  OpenViBE::CIdentifier(0x1762575C, 0x234FCEA9)

#define OVTK_Algorithm_ScenarioExporter_NodeId_Links                                    OpenViBE::CIdentifier(0x5B4FF75F, 0x7FB1E0DA)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Link                                     OpenViBE::CIdentifier(0x7E290F90, 0xEB62C398)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Link_Identifier                          OpenViBE::CIdentifier(0x51FEC159, 0x0958BF76)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Link_Source                              OpenViBE::CIdentifier(0xD7E0F55E, 0x576625E3)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Link_Source_BoxIdentifier                OpenViBE::CIdentifier(0x49A048C0, 0x564E3FF3)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Link_Source_BoxOutputIndex               OpenViBE::CIdentifier(0x6C4C2561, 0x0C128F04)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Link_Target                              OpenViBE::CIdentifier(0x231E8241, 0x89F06614)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Link_Target_BoxIdentifier                OpenViBE::CIdentifier(0xDB6D995F, 0xE514B76A)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Link_Target_BoxInputIndex                OpenViBE::CIdentifier(0x2DEDF2E1, 0x76778F6B)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Link_Attributes                          OpenViBE::CIdentifier(0x3B3700A0, 0x51159BB0)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Link_Attribute                           OpenViBE::CIdentifier(0xA1487B45, 0x88C442B6)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Link_Attribute_Identifier                OpenViBE::CIdentifier(0x03710320, 0x0A550AE0)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Link_Attribute_Value                     OpenViBE::CIdentifier(0x3831E536, 0x6E0C9282)

#define OVTK_Algorithm_ScenarioExporter_NodeId_Scenario_Attributes                      OpenViBE::CIdentifier(0x06B858A3, 0xE3F6B199)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Scenario_Attribute                       OpenViBE::CIdentifier(0x195DF0C2, 0x01071746)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Scenario_Attribute_Identifier            OpenViBE::CIdentifier(0x66A99FF0, 0x402B6F19)
#define OVTK_Algorithm_ScenarioExporter_NodeId_Scenario_Attribute_Value                 OpenViBE::CIdentifier(0xA4795600, 0x31AFDFB1)

#define OVTK_Algorithm_ScenarioExporter_NodeId_VisualisationTree                        OpenViBE::CIdentifier(0x0EBD3609, 0x24BA5E97)
#define OVTK_Algorithm_ScenarioExporter_NodeId_VisualisationWidget                      OpenViBE::CIdentifier(0x12A84EEB, 0x69766575)
#define OVTK_Algorithm_ScenarioExporter_NodeId_VisualisationWidget_Identifier           OpenViBE::CIdentifier(0x66FA2B30, 0x4D1672BE)
#define OVTK_Algorithm_ScenarioExporter_NodeId_VisualisationWidget_Name                 OpenViBE::CIdentifier(0x12AA197C, 0x33757384)
#define OVTK_Algorithm_ScenarioExporter_NodeId_VisualisationWidget_Type                 OpenViBE::CIdentifier(0x32F77316, 0x32F149DF)
#define OVTK_Algorithm_ScenarioExporter_NodeId_VisualisationWidget_ParentIdentifier     OpenViBE::CIdentifier(0x18F387AC, 0x7DB9250F)
#define OVTK_Algorithm_ScenarioExporter_NodeId_VisualisationWidget_Index                OpenViBE::CIdentifier(0xC2011BE7, 0x31D98611)
#define OVTK_Algorithm_ScenarioExporter_NodeId_VisualisationWidget_BoxIdentifier        OpenViBE::CIdentifier(0xE5291CBD, 0x734A3441)
#define OVTK_Algorithm_ScenarioExporter_NodeId_VisualisationWidget_NumChildren          OpenViBE::CIdentifier(0xF6D07A2A, 0x92628DF5)
#define OVTK_Algorithm_ScenarioExporter_NodeId_VisualisationWidget_Attributes           OpenViBE::CIdentifier(0x56A082C5, 0x7B61F7E8)
#define OVTK_Algorithm_ScenarioExporter_NodeId_VisualisationWidget_Attribute            OpenViBE::CIdentifier(0xFE0A0425, 0x3A9F017B)
#define OVTK_Algorithm_ScenarioExporter_NodeId_VisualisationWidget_Attribute_Identifier OpenViBE::CIdentifier(0x074544F4, 0x0C5B3F76)
#define OVTK_Algorithm_ScenarioExporter_NodeId_VisualisationWidget_Attribute_Value      OpenViBE::CIdentifier(0x2A2A7A67, 0xD1F930E3)

#endif // __OpenViBEToolkit_ScenarioIO_H__
